name: Denopendabot

description: Keeps your Deno projects up-to-date

inputs:
  token:
    description: Access token authorized to run workflows
    required: true

  user-token:
    description: Personal access token authorized to update workflows
    required: false

  repository:
    description: Repository to update dependencies
    required: true
    default: ${{ github.repository }}

  base-branch:
    description: Branch to update
    required: true
    default: main

  working-branch:
    description: Working branch for Denopendabot
    required: true
    default: denopendabot

runs:
  using: composite

  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.26.1 # @denopendabot denoland/deno

    - name: Run Denopendabot
      run: >
        deno run -q --allow-env --allow-net
        https://deno.land/x/denopendabot@0.5.9/main.ts # @denopendabot hasundue/denopendabot
        ${{ inputs.repository }}
        --base ${{ inputs.base-branch }}
        --branch ${{ inputs.working-branch }}
        --token ${{ inputs.token }}
        --user-token ${{ inputs.user-token }}
      shell: bash

branding:
  icon: 'refresh-cw'
  color: 'gray-dark'
