name: Denopendabot

description: Keeps your Deno projects up-to-date

inputs:
  token:
    description: Personal access token authorized to update workflows
    required: true

  repository:
    description: Repository to update dependencies
    required: true
    default: ${{ github.repository }}

  base-branch:
    description: Branch to update
    required: true
    default: main

  working-branch:
    description: Working branch for Denopendabot
    required: true
    default: main

runs:
  using: composite

  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.26.1 # @denopendabot denoland/deno

    - name: Run Denopendabot
      run: >
        deno run -q --allow-env --allow-net ./main.ts ${{ inputs.repository }}
        --base ${{ intputs.base-branch }}
        --branch ${{ intputs.working-branch }}
        --token ${{ inputs.token }}
      shell: bash
