name: Denopendabot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # TODO: modify to your convenient time
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: hasundue/denopendabot@0.8.1 # @denopendabot hasundue/denopendabot
        mode: app
