name: CI/CD

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    needs: test
    secrets: inherit

  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml
    needs: deploy
    secrets: inherit

  release:
    name: Release
    uses:  ./.github/workflows/release.yml
    needs: integration
    secrets: inherit
    if: github.repository_owner == 'hasundue'

