name: CI/CD

on:
  push:
    branches: 
      - main
    paths:
      - '**.ts'
      - '**.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy-staging:
    name: Deploy
    if: github.repository_owner == 'hasundue'
    uses: ./.github/workflows/deploy.yml
    needs: test
    secrets: inherit
    with:
      deployment: staging

  integration:
    name: Integration
    if: github.repository_owner == 'hasundue'
    uses: ./.github/workflows/integration.yml
    needs: deploy
    secrets: inherit

  release:
    name: Release
    if: github.repository_owner == 'hasundue'
    uses:  ./.github/workflows/release.yml
    needs: integration
    secrets: inherit

  deploy-production:
    name: Deploy
    if: github.repository_owner == 'hasundue'
    uses: ./.github/workflows/deploy.yml
    needs: release
    secrets: inherit
    with:
      deployment: production
