name: CI

on:
  pull_request:
    branches: 
      - main
    paths:
      - '**.ts'
      - '**.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    name: Deploy
    if: ${{ github.repository_owner == 'hasundue' }}
    uses: ./.github/workflows/deploy.yml
    needs: test
    secrets: inherit
    with:
      deployment: staging

  integration:
    name: Integration
    if: ${{ github.repository_owner == 'hasundue' }}
    uses: ./.github/workflows/integration.yml
    needs: deploy
    secrets: inherit
