name: CI/CD

on:
  pull_request:
    branches: 
      - main
    paths:
      - '**.ts'
      - '**.yml'
  push:
    branches:
      - staging

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    name: Staging
    if: github.event_name == 'push' || github.event.pull_request.user.login == 'hasundue'
    uses: ./.github/workflows/deploy.yml
    with:
      deployment: staging
    secrets: inherit

  integration:
    name: Integration
    needs: 
      - test
      - deploy
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  delivery:
    name: Delivery
    if: github.event_name == 'push'
    needs: integration
    uses: ./.github/workflows/delivery.yml
    secrets: inherit
