name: CI

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: test
    secrets: inherit

  integration:
    uses: ./.github/workflows/integration.yml
    needs: deploy
    secrets: inherit

  release:
    uses:  ./.github/workflows/release.yml
    if: github.repository_owner == 'hasundue' && github.ref_name == 'main'
    needs: integration
    secrets: inherit
