name: CI

on:
  push:
    branches: 
      - main

env:
  APP_ID: ${{ secrets.APP_ID }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    name: Release
    needs: test
    uses: ./.github/workflows/release.yml
    secrets: inherit
