name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Denopendabot
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.0

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno task test --coverage=./coverage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create coverage report
        run: deno coverage ./coverage --lcov > ./coverage.lcov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.lcov

  release:
    name: Release
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.0

      - name: Semantic Release
        run: >
          deno run --allow-env --allow-net
          https://deno.land/x/denomantic_release@0.1.0/main.ts
          ${{ github.repository }}
          --token ${{ secrets.GITHUB_TOKEN }}
