name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Denopendabot
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno task test

  release:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Semantic Release
        run: >
          deno run --allow-env --allow-net
          https://deno.land/x/denomantic_release@0.1.0/main.ts
          ${{ github.repository }}
          --token ${{ secrets.GITHUB_TOKEN }}
