name: CI

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    name: Staging
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.user.login == 'hasundue' ||
      github.event.pull_request.user.login == 'denopendabot[bot]'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  integration:
    name: Integration
    needs: 
      - test
      - deploy
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  delivery:
    name: Dispatch CD
    if: github.event_name == 'workflow_dispatch'
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CD
          token: ${{ secrets.GH_TOKEN }}
          ref: main
