name: Integration

on:
  workflow_call:
  workflow_dispatch:

jobs:
  module:
    name: Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.2 # @denopendabot denoland/deno

      - name: Cache dependencies
        run: deno cache integration/mod_test.ts

      - name: Run tests
        run: deno task test integration/mod_test.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  action:
    name: Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.2 # @denopendabot denoland/deno

      - name: Create test action
        run: deno run -A integration/build.ts

      - name: Run action
        uses: ./integration
        with:
          mode: action
          base-branch: test
          working-branch: test-action
          labels: test
          release: 1.0.0

  app:
    name: App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Run App
        uses: ./
        with:
          mode: app
          base-branch: test
          working-branch: test-app
          release: 1.0.0
          auto-merge: all
