name: Integration

on:
  workflow_call:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  module:
    name: Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.27.0 # @denopendabot denoland/deno

      - name: Cache dependencies
        run: deno cache -q integration/mod_test.ts

      - name: Run tests
        run: deno task test integration/mod_test.ts

  action:
    name: Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.27.0 # @denopendabot denoland/deno

      - name: Create test action
        run: deno run -q -A integration/build.ts

      - name: Create a branch for testing
        run: git branch -C main test-action

      - name: Run action
        uses: ./integration
        with:
          mode: action
          base-branch: test-action
          working-branch: test-action-${{ github.ref }}
          include: integration/src/deps.ts
          labels: test

      - name: Delete the branch
        run: git branch -D test-action-${{ github.ref }}

  app:
    name: App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.27.0 # @denopendabot denoland/deno

      - name: Cache dependencies
        run: deno cache -q integration/app_test.ts

      - name: Run tests
        run: deno task test integration/app_test.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
