name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release

    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    outputs:
      released: ${{ steps.run.outputs.released }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.2 # @denopendabot denoland/deno

      - name: Run denomantic-release
        id: run
        run: >
          deno run -q --allow-env --allow-net --allow-write
          https://deno.land/x/denomantic_release@0.6.1/main.ts
          ${{ github.repository }}
          --token ${{ secrets.GITHUB_TOKEN }}

      - name: Run Denopendabot 
        if: ${{ steps.run.outputs.needs_update }}
        run: >
          deno run -q --allow-env --allow-net ./main.ts
          ${{ github.repository }}
          --token ${{ secrets.GITHUB_TOKEN }}
          --user-token ${{ secrets.GH_TOKEN }}
          --release ${{ steps.run.outputs.version }}
