name: Stage

on:
  push:
    branches: 
      - main
    paths:
      - '**.ts'
      - '.github/workflows/test.yml'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/integration.yml'
      - '.github/workflows/deploy.yml'

jobs:
  stage:
    name: Stage

    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          force: true

      - name: Dispatch CI/CD
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI/CD
          token: ${{ secrets.GH_TOKEN }}
          ref: staging
