name: Update

on:
  workflow_dispatch:

jobs:
  test:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Denopendabot
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.0 # @denopendabot denoland/deno

      - name: Run Denopendabot
        run: >
          deno run -q --allow-env --allow-net --allow-read
          https://pax.deno.dev/hasundue/denopendabot/main.ts
          ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

