name: Denopendabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          mode: app
          auto-merge: all
