name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "23 23 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Denopendabot
        uses: actions/checkout@v3.1.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.1 # @denopendabot denoland/deno

      - name: Run Denopendabot
        run: >
          deno run -q --allow-env --allow-net ./main.ts
          ${{ github.repository }}
          --user-token ${{ secrets.GH_TOKEN }}
